

export const ACTIVATE_CODE_SCENE = 'ACTIVATE_CODE_SCENE'
export const MAIN_SCENE = 'MAIN_SCENE'


export const IMPROVE_LIMITS_SCENE = 'IMPROVE_LIMITS_SCENE'

export const SUPPORT_SCENE = 'SUPPORT_SCENE'

export const ADD_USER_CHANNEL_ACTION_SCENE = 'ADD_USER_CHANNEL_ACTION_SCENE'
export const ADD_CHANNELS_TO_REWRITE_SCENE = 'ADD_CHANNELS_TO_REWRITE_SCENE'

export const MAIN_CHANNEL_SCENE = 'MAIN_CHANNEL_SCENE'

export const ADD_USER_CHANNEL_SCENE = 'ADD_USER_CHANNEL_SCENE'

export const EDIT_CHANNEL_TO_REWRITE_SCENE = 'EDIT_CHANNEL_TO_REWRITE_SCENE'

export const MAIN_CHANNELS_TO_REWROTE_SCENE = 'MAIN_CHANNELS_TO_REWROTE_SCENE'

export const ADD_CHANNEL_TO_REWRITE_SCENE = 'ADD_CHANNEL_TO_REWRITE_SCENE'

export const DELETE_USER_CHANNEL_SCENE = 'DELETE_USER_CHANNEL_SCENE'