import { CategoryRepositoryLinkConfig } from '../repository/category/category.repository.link.config';

export const CONTENT_AGENCY_CLIENT = 'CONTENT_AGENCY_CLIENT';

export const STORAGE_CLIENT = 'STORAGE_CLIENT';

export const USER_REPOSITORY = 'USER_REPOSITORY';

//MANAGER

export const CHANNEL_MANAGER_LINK_CONFIG = 'CHANNEL_MANAGER_LINK_CONFIG';
export const CHANNEL_MANAGER = 'CHANNEL_MANAGER';

export const USER_MANAGER = 'USER_MANAGER';

export const USER_MANAGER_LINK_CONFIG = 'USER_MANAGER_LINK_CONFIG';

export const CREATE_USER_URL = 'CREATE_USER_URL';

export const CHECK_CHANNELS_URL = 'CHECK_CHANNELS_URL';

//REPOSITORY

export const MOCK_REPOSITORY = 'MOCK_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const CATEGORY_REPOSITORY_LINK_CONFIG = 'CATEGORY_REPOSITORY_LINK_CONFIG';

export const CONTENT_REWRITER = 'CONTENT_REWRITER';

export const LINK_VALIDATOR = 'LINK_VALIDATOR';

export const ADD_CHANNELS_PROMO_CONFIG = 'ADD_CHANNELS_PROMO_CONFIG';
