
export const ADD_CHANNEL_URL = 'ADD_CHANNEL_URL'
export const DELETE_CHANNEL_URL = 'DELETE_CHANNEL_URL'
export const DELETE_CHANNEL_TO_REWRITE_URL = 'DELETE_CHANNEL_TO_REWRITE_URL'

export const GET_CATEGORIES_URL = 'GET_CATEGORIES_URL'

export const GET_USER_URL = 'GET_USER_URL'

export const REWRITE_CONTENT_URL = 'REWRITE_CONTENT_URL'
export const CONTENT_REWRITER_LINK_CONFIG = 'CONTENT_REWRITER_LINK_CONFIG'

export const LIMIT_POSTS = 'LIMIT_POSTS'