export const ADD_USER_CHANNEL_ACTION_PAGE = 'ADD_USER_CHANNEL_ACTION_PAGE';
export const ADD_CHANNELS_TO_REWRITE_PAGE = 'ADD_CHANNELS_TO_REWRITE_PAGE';

export const MAIN_CHANNEL_PAGE = 'MAIN_CHANNEL_PAGE';

export const ADD_USER_CHANNEL_PAGE = 'ADD_USER_CHANNEL_PAGE';

export const MAIN_CHANNEL_TO_REWRITE_PAGE = 'MAIN_CHANNEL_TO_REWRITE_PAGE';

export const MAIN_CHANNELS_TO_REWRITE_PAGE = 'MAIN_CHANNELS_TO_REWRITE_PAGE';

export const ADD_CHANNEL_TO_REWRITE_PAGE = 'ADD_CHANNEL_TO_REWRITE_PAGE';

export const DELETE_USER_CHANNEL_PAGE = 'DELETE_USER_CHANNEL_PAGE';

export const EDIT_CHANNEL_TO_REWRITE_PAGE = 'EDIT_CHANNEL_TO_REWRITE_PAGE';
export const EDIT_PROMPT = 'EDIT_PROMPT'

export const ADD_CHANNEL_CATEGORY = 'ADD_CHANNEL_CATEGORY'

export const ACTIVATE_CODE = 'ACTIVATE_CODE'
export const IMPROVE_LIMITS = 'IMPROVE_LIMITS'

export const SUPPORT = 'SUPPORT'

export const START = 'START'

export const ADD_CHANNELS_PROMO = 'ADD_CHANNELS_PROMO'